### ISSUE TITLE
Bug in greg tests

### ISSUE THREAD

**Issue by assapir** [hebcal/hdate-js#1]
The test [here](https://github.com/hebcal/hdate-js/blob/3f28afa9f3a1ee021f9c483f9e9c399544736e37/test/greg.spec.js#L12C3-L12C55) is running with the following params: 
```js
t.is(greg.greg2abs(new Date(1888, 11, 31)), 689578);
```
But there is no 31st day in November.

**Comment by mjradwin** [comment]
`new Date(1888, 11, 31)` does not correspond to the 31st day of November, it's the 31st day of December.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

**Comment by assapir** [comment]
Yeah, I just figured my mistake, sorry
